In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

In [ ]:
np.linalg.norm(a)

In [ ]:
#Cauchy-Schwarz inequality 
np.dot(a,b) / (np.linalg.norm(a)*np.linalg.norm(b))

In [28]:
np.matrix('1,2,-1,-1; 2,4,-2,3; -1,1,-2,4')

matrix([[ 1,  2, -1, -1],
        [ 2,  4, -2,  3],
        [-1,  1, -2,  4]])

MATRIX VECTOR MULTIPLICATION

In [ ]:
A = np.array([[ 1,  2, -1, -1], [ 2,  4, -2,  3], [-1,  1, -2,  4]])
print(A)
print(A.shape)
print(A[0])
print(A[1])
print(A[2])
print(A[0].shape)

In [ ]:
x = np.array([-1,1,1,0])
print(x)
print(np.dot(A,x))

In [ ]:
#above [0,0,0] the rows of A is perpendicular to x

TENSORS

In [ ]:
T = np.array([[[74,128],[79,116],[71,116]],
              [[18,118],[82,124],[72,128]],
              [[84,138],[84,130],[74,120]],
              [[82,126],[76,156],[82,132]]])
print(T)
print(T.shape)
print(T[0])
print(T[0][0])

In [ ]:
#create x such that np.dot(T,x)
x1 = np.array([1, 1])
print(T)
print(x)
print(T.shape)
print(x.shape)
np.dot(T,x1)

In [ ]:
T.reshape(3,2,4)

Linear combination of column of matrix A


In [ ]:
#Linear combination of column of matrix A
print(A)
print(x)
print(np.dot(A,x))
#np.matmul(A,x)
print(A[:,0]*x[0] + A[:,1]*x[1] + A[:,2]*x[2] + A[:,3]*x[3])    #linear combination of column and matrix, instead of typing this 
np.sum(x[range(4)] * A[ :, range(4)])

In [18]:
#4 timestamps, 3 patients, 2 features
T = np.array([[[74,128],[79,116],[71,116]],
              [[78,118],[82,124],[72,128]],
              [[84,138],[84,130],[74,120]],
              [[82,126],[76,156],[82,132]]])

(1) 0th axis of size 3 corresponded to patients;

(2) 1st axis of size 4 corresponded to time stamps;

(3) 2nd axis of size 2 corresponded to features.

What does the output of T_reshaped[0] indicate now? 

What does the output of T_reshaped[:, :, 1] 
indicate?

In [19]:
T_reshaped = T.transpose(1,2,0)    #(3,2,4)  
T_reshaped

array([[[ 74,  78,  84,  82],
        [128, 118, 138, 126]],

       [[ 79,  82,  84,  76],
        [116, 124, 130, 156]],

       [[ 71,  72,  74,  82],
        [116, 128, 120, 132]]])

In [20]:
T_reshaped[0]   #0th patient's information across all features and time stamps 

array([[ 74,  78,  84,  82],
       [128, 118, 138, 126]])

In [21]:
T_reshaped[:, :, 1]    #1st timestamps value for all patients and features

array([[ 78, 118],
       [ 82, 124],
       [ 72, 128]])

In [ ]:
#transpose : realign
#reshape : to change structure

In [25]:
T_reshaped = T.transpose(2,0,1)  #features, timestamps, patients
T_reshaped


array([[[ 74,  79,  71],
        [ 78,  82,  72],
        [ 84,  84,  74],
        [ 82,  76,  82]],

       [[128, 116, 116],
        [118, 124, 128],
        [138, 130, 120],
        [126, 156, 132]]])

In [26]:
T_reshaped[0]

array([[74, 79, 71],
       [78, 82, 72],
       [84, 84, 74],
       [82, 76, 82]])

In [27]:
T_reshaped[:,2,:]

array([[ 84,  84,  74],
       [138, 130, 120]])

In [30]:
A = np.matrix('1,2,3; 4,5,6')
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [32]:
B = np.matrix('7,10; 8,11; 9,12')
B

matrix([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [33]:
np.matmul(A,B)

matrix([[ 50,  68],
        [122, 167]])

In [43]:
#Tensor matrix product
T = np.array([[[74,128],[79,116],[71,116]],
              [[78,118],[82,124],[72,128]],
              [[84,138],[84,130],[74,120]],
              [[82,126],[76,156],[82,132]]])

X = np.array([[0,1],[1,1]])
print(X)
print(np.dot(T,X))   
print(T.shape)
print(X.shape)

[[0 1]
 [1 1]]
[[[128 202]
  [116 195]
  [116 187]]

 [[118 196]
  [124 206]
  [128 200]]

 [[138 222]
  [130 214]
  [120 194]]

 [[126 208]
  [156 232]
  [132 214]]]
(4, 3, 2)
(2, 2)


In [47]:
T1 = np.array([[[74,128],[79,116],[71,116]],
              [[78,118],[82,124],[72,128]],
              [[84,138],[84,130],[74,120]],
              [[82,126],[76,156],[82,132]]])
T2 = np.array([[[1,1],[1,1],[1,1]],
              [[1,1],[1,1],[1,1]],
              [[1,1],[1,1],[1,1]]])
T2.shape
print(np.dot(T1,T2))

ValueError: shapes (4,3,2) and (3,3,2) not aligned: 2 (dim 2) != 3 (dim 1)