In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [4]:
np.linalg.norm(a)

3.7416573867739413

In [5]:
#Cauchy-Schwarz inequality 
np.dot(a,b) / (np.linalg.norm(a)*np.linalg.norm(b))

0.9746318461970762

In [7]:
np.matrix('1,2,-1,-1; 2,4,-2,3; -1,1,-2,4')

matrix([[ 1,  2, -1, -1],
        [ 2,  4, -2,  3],
        [-1,  1, -2,  4]])

MATRIX VECTOR MULTIPLICATION

In [15]:
A = np.array([[ 1,  2, -1, -1], [ 2,  4, -2,  3], [-1,  1, -2,  4]])
print(A)
print(A.shape)
print(A[0])
print(A[1])
print(A[2])
print(A[0].shape)

[[ 1  2 -1 -1]
 [ 2  4 -2  3]
 [-1  1 -2  4]]
(3, 4)
[ 1  2 -1 -1]
[ 2  4 -2  3]
[-1  1 -2  4]
(4,)


In [43]:
x = np.array([-1,1,1,0])
print(x)
print(np.dot(A,x))

[-1  1  1  0]
[0 0 0]


In [ ]:
#above [0,0,0] the rows of A is perpendicular to x

TENSORS

In [23]:
T = np.array([[[74,128],[79,116],[71,116]],
              [[18,118],[82,124],[72,128]],
              [[84,138],[84,130],[74,120]],
              [[82,126],[76,156],[82,132]]])
print(T)
print(T.shape)
print(T[0])
print(T[0][0])

[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 18 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]]
(4, 3, 2)
[[ 74 128]
 [ 79 116]
 [ 71 116]]
[ 74 128]


In [40]:
#create x such that np.dot(T,x)
x1 = np.array([1, 1])
print(T)
print(x)
print(T.shape)
print(x.shape)
np.dot(T,x1)

[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 18 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]]
[1 1]
(4, 3, 2)
(2,)


array([[202, 195, 187],
       [136, 206, 200],
       [222, 214, 194],
       [208, 232, 214]])

In [41]:
T.reshape(3,2,4)

array([[[ 74, 128,  79, 116],
        [ 71, 116,  18, 118]],

       [[ 82, 124,  72, 128],
        [ 84, 138,  84, 130]],

       [[ 74, 120,  82, 126],
        [ 76, 156,  82, 132]]])

Linear combination of column of matrix A


In [53]:
#Linear combination of column of matrix A
print(A)
print(x)
print(np.dot(A,x))
#np.matmul(A,x)
print(A[:,0]*x[0] + A[:,1]*x[1] + A[:,2]*x[2] + A[:,3]*x[3])    #linear combination of column and matrix, instead of typing this 
np.sum(x[range(4)] * A[ :, range(4)])

[[ 1  2 -1 -1]
 [ 2  4 -2  3]
 [-1  1 -2  4]]
[-1  1  1  0]
[0 0 0]
[0 0 0]


0